---
# Dependabot configuration file
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
enable-beta-ecosystems: true
updates:
  # Enable version updates for Bun
  - package-ecosystem: "bun"
    # Look for bun.lock file in the root directory
    directory: "/"
    # Check for updates daily
    schedule:
      interval: "daily"
    assignees:
      - "cedricziel"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflow files in the .github/workflows directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"
    assignees:
      - "cedricziel"
