name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_GHCR: ghcr.io
  IMAGE_NAME: cedricziel/aha-mcp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_GHCR }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr,prefix=pr-
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Docker image test
      run: |
        # Test that the image can start and respond to --help
        # Use the first tag from the metadata output (works for both PR and main builds)
        IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
        docker run --rm $IMAGE_TAG --help

    - name: Test Docker image in stdio mode
      run: |
        # Test basic functionality without credentials
        IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
        timeout 5s docker run --rm $IMAGE_TAG --mode stdio || true

    - name: Test Docker image in SSE mode
      run: |
        # Test SSE mode startup
        IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
        docker run --rm -d --name aha-mcp-test -p 3001:3001 $IMAGE_TAG --mode sse
        sleep 5
        # Check health endpoint
        curl -f http://localhost:3001/health || exit 1
        # Check info endpoint
        curl -f http://localhost:3001/ || exit 1
        # Cleanup
        docker stop aha-mcp-test

